server:
  port: 3333

flowable:
  ##关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_flowable1?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver